version: '3.8'

services:
  mongo:
    build:
      context: ./database
    image: snapdocs-mongo-custom:latest
    container_name: snapdocs-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - snapdocs-backend-network

  backend:
    build:
      context: ./backend/services/auth-service
    image: snapdocs-auth-service:latest
    container_name: snapdocs-auth-container-backend
    env_file:
      - ./backend/services/auth-service/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - snapdocs-backend-network

  document-service:
    build:
      context: ./backend/services/document-service
    image: snapdocs-document-service:latest
    container_name: snapdocs-document-container
    env_file:
      - ./backend/services/document-service/app/.env
    ports:
      - "8001:8001"
    volumes:
      - document-uploads:/app/uploads
      - ./uploads:/app/uploads/host  # Additional mapping for local development access
    depends_on:
      - mongo
      - backend
    networks:
      - snapdocs-backend-network

  frontend:
    build:
      context: ./frontend/snapdocs-app
    image: snapdocs-frontend-app:latest
    container_name: snapdocs-frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
      - document-service
    networks:
      - snapdocs-backend-network

volumes:
  mongo-data:
  document-uploads:

networks:
  snapdocs-backend-network:
    driver: bridge